### ISSUE TITLE
ParsePQLog.txt is missing

### ISSUE THREAD

**Issue by c-rush** [PacktPublishing/Microsoft-Power-BI-Performance-Best-Practices#3]
Chapter 8's section "Analyzing The Power Query Logs" references `ParsePQLog.txt`, a function for flattening query trace logs. I cannot find it under Chapter08 or anywhere else in the repository.

**Edit** It appears the function is available within the sample file `Query Diagnostics.pbix`.

**Comment by BhavikMerchant** [comment]
Thank you! Missing file has been added now.
